### ISSUE TITLE
Bucket policy fix?

### ISSUE THREAD

**Issue by jedsundwall** [peacecorps/peace-corps-countries-api#3]
I'm getting "access denied" errors on the file URLs exposed by your API (e.g. http://files.peacecorps.gov/uploads/banners/albania.jpg). It seems like you might want to update your bucket policy to make those files readable by anyone.

**Comment by sshami** [comment]
Thanks for reporting. The example you provided seems to be the incorrect URL to the assets. It’s missing the ‘countries’ directory in the URL.

Can you confirm that you are getting the following URL for the banner image asset:
http://files.peacecorps.gov/uploads/banners/albania.jpg

You should be getting the following URL instead. Are you not getting this when you call the API?
http://files.peacecorps.gov/uploads/countries/banners/albania.jpg

**Comment by jedsundwall** [comment]
Ha! This is entirely my mistake. I had misread the URLs during your presentation. If only Firefox let you zoom in on the json! ;)

Carry on.
